site_name: Matrix Models via QC, DL, MC
site_author: "@erinaldi"
site_description: "Supplementary figures and tables to the arxiv publication 2107.XXXXX"
nav:
  - Home: index.md
  - Quantum Computing: qc.md
  - Deep Learning: dl.md
  - Lattice Monte Carlo: 
    - mc/mc.md
    - Energy figures: mc/figures.md
    - Energy tables: mc/tables.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  palette:
    - primary: lime
    - accent: indigo
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js